enqueue:
    default:
        transport:
            dsn: '%env(resolve:ENQUEUE_DSN)%'
            global:
                group.id: 'myapp'
                metadata.broker.list: "%env(KAFKA_BROKER_LIST)%"
                security.protocol: 'plaintext'
            topic:
                auto.offset.reset: beginning
            commit_async: true
        client: ~
