version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
            - ../.docker/mysql/init-db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app
    php-fpm:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - '2181:2181'
        networks:
            - symfony_app
    kafka:
        image: wurstmeister/kafka:2.12-2.5.0
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,EXTERNAL://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "messages:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            - symfony_app
volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
